server:
  port: 8086

spring:
  application:
    name: discovery

eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://server1:8086/eureka
       
  server:
    waitTimeInMsWhenSyncEmpty: 0
    